org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=alloyed
mod.name=Create Alloyed
mod.group=com.molybdenum
mod.version=3.0.0
mod.test_build=2

deps.fabric-loader=0.18.4

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=KgKqTqPj
publish.curseforge=981829
#publish.additionalVersions=