deps.minecraft=1.21.1
deps.neoforge=21.1.211
deps.parchment=1.21.1:2024.11.17

mod.mc_dep_forgelike=[1.21, 1.21.2]

deps.emi = 1.1.18
deps.jei = 19.27.0.340

deps.create = 6.0.9-215
deps.ponder = 1.0.81
deps.flywheel = 1.0.6
deps.registrate = MC1.21-1.3.0+67

deps.fd = 1.21.1-1.2.10
deps.create_deco = 2.1.2
deps.yacl=3.8.2+1.21.1
deps.spears=FROwtXRs
deps.bigger_fish=qNCuRvVE